include: package:yumemi_lints/flutter/3.27/recommended.yaml

analyzer:
  plugins: # https://riverpod.dev/docs/introduction/getting_started#enabling-riverpod_lintcustom_lint
    - custom_lint
  errors: # https://pub.dev/packages/freezed#install
    invalid_annotation_target: ignore

linter:
  rules:

    # ウィジェットのデバッグ情報が不足している場合の警告
    diagnostic_describe_all_properties: false

    # asyncに関する警告
    discarded_futures: false

    # BuildContextに関する警告
    use_build_context_synchronously: false
