targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - duplicate_ignore
      json_serializable:
        options:
          field_rename: snake
