// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmy8Qu1OUTmFzghPc5MK5kBFZKkQEmoyY',
    appId: '1:505064710022:android:870959193ff3c5e3145607',
    messagingSenderId: '505064710022',
    projectId: 'food-gram-407205',
    databaseURL: 'https://food-gram-407205-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'food-gram-407205.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsr3Q4ZAJITuGz0lpfh5MrbSVCPmQvZpw',
    appId: '1:505064710022:ios:759e728c10469001145607',
    messagingSenderId: '505064710022',
    projectId: 'food-gram-407205',
    databaseURL: 'https://food-gram-407205-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'food-gram-407205.appspot.com',
    androidClientId: '505064710022-tijnbvin54d630t9sjaioe0igrdrdme3.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodGramApp.RunnerTests',
  );
}
