name: Auto Author Assign

on:
  pull_request:
    types: [opened, reopened]

jobs:
  assign-author:
    name: Auto Author Assign
    runs-on: ubuntu-22.04
    steps:
      - uses: toshimaru/auto-author-assign@16f0022cf3d7970c106d8d1105f75a1165edb516 #2.1.1s