name: Format and Analyze

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup FVM
        uses: leoafarias/fvm@v2
        with:
          flutter-version: '3.27.1'

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ~/.pub
            build/
            ~/.fvm
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Install dependencies
        run: fvm flutter pub get

      - name: Check formatting
        run: |
          # 生成ファイルを除外してフォーマットチェック
          fvm flutter format --set-exit-if-changed \
            --exclude-dir=lib/gen \
            --exclude-dir=lib/generated \
            --exclude=lib/firebase_options.dart \
            .

      - name: Analyze project source
        run: |
          # 生成ファイルを除外して静的解析
          fvm flutter analyze \
            --exclude-dir=lib/gen \
            --exclude-dir=lib/generated \
            --exclude=lib/firebase_options.dart

      - name: Check for outdated dependencies
        run: fvm flutter pub outdated

      - name: Check generated files
        run: |
          # 生成ファイルが直接編集されていないかチェック
          if git diff --name-only | grep -E "lib/gen/|lib/firebase_options.dart"; then
            echo "Error: Generated files have been modified directly. Please use the appropriate CLI commands to regenerate them."
            exit 1
          fi

