name: test

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize ]
  push:
    branches:
      - main

env:
  FLUTTER_VERSION: '3.10.2'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Retrieve the secret and decode it to a file
        env:
          APP_ENV: ${{ secrets.APP_ENV }}
          ACCONT_BASE64: ${{ secrets.DEV_ENV }}
          ATTRACTION_BASE64: ${{ secrets.PROD_ENV }}
        run: |
          if [ -n "$APP_ENV" ]; then
            echo $APP_ENV | base64 --decode > .env || echo "Invalid APP_ENV base64 string"
          fi
          if [ -n "$ACCONT_BASE64" ]; then
            echo $ACCONT_BASE64 | base64 --decode > .env.dev || echo "Invalid ACCONT_BASE64 string"
          fi
          if [ -n "$ATTRACTION_BASE64" ]; then
            echo $ATTRACTION_BASE64 | base64 --decode > .env.prod || echo "Invalid ATTRACTION_BASE64 string"
          fi

      # - name: Retrieve the secret and decode it to a file
      #   env:
      #     APP_ENV: ${{ secrets.APP_ENV }}
      #     ACCONT_BASE64: ${{ secrets.DEV_ENV }}
      #     ATTRACTION_BASE64: ${{ secrets.PROD_ENV }}

      #   run: |
      #     echo $APP_ENV | base64 --decode > .env
      #     echo $DEV_ENV_BASE64 | base64 --decode > .env.dev
      #     echo $PROD_ENV_BASE64 | base64 --decode > .env.prod


      - name: fvm
        uses: kuhnroyal/flutter-fvm-config-action@v1
        id: fvm-config-action

      - name: install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}

      - name: Install dependencies
        run: |
          flutter pub get

      - name: build runner
        run: |
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Test
        run: |
          flutter test